### ISSUE TITLE
画像読み込みで、読み込むまでは適当な画像を設定しておく

### ISSUE THREAD

**Issue by kobapi28** [jphacks/C_2006#142]
## 追加する機能

- 画像データがくるまでは違う画像をおいておく

## 編集するファイル

-

**Comment by takumma** [comment]
- imageUrlの初期値にサンプル画像入れておく
- postsから取得するときにimageUrlじゃない別の変数に入れる
- storageから取得したらimageUrlに代入する
でどうですか
