### ISSUE TITLE
splashがひどい

### ISSUE THREAD

**Issue by kobapi28** [jphacks/C_2006#57]
## どういったバグが起きているか

- 画像見て。

## バグを直した後の挙動

- たぶん、サイズとかちゃんとしてやらないといけない

## 修正すべきファイル

- いろんなサイズの画像を用意する

## スクリーンショット
![Screenshot from 2020-11-01 17-18-24](https://user-images.githubusercontent.com/60056125/97798120-85aecf00-1c66-11eb-9a1b-d65d97b78e77.png)

**Comment by takumma** [comment]
これアスペクト比固定とかでできないんですか？

**Comment by kobapi28** [comment]
えーどうなんだろ、ちょっとしらべます
