### ISSUE TITLE
firebase.jsを置く

### ISSUE THREAD

**Issue by takumma** [jphacks/C_2006#69]
## 追加する機能

- firebase.jsを隠してるのダサいので、.envファイルにかきこんでそれを読み込むようにする

## 編集するファイル

- .env, .gitignoreなど

**Comment by takumma** [comment]
普通に公開するかー。そのかわりルールを書き換えて置きます。

**Comment by kobapi28** [comment]
なんか別にやらんくてよくね？って感じです。僕的には

**Comment by takumma** [comment]
localhostのポートとか変更するのめんどくさいしとりあえずこのままいきます（.envにしてほしければissue立ててください）。
でもセキュリティルールはもう少し考えないといけないと思います。
とりあえずこのissueは閉じます。
